server:
  port: 9291
spring:
  application:
    name: market-server
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: 123456
      username: root
      url: jdbc:mysql://localhost:3306/supermarket?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useSSL=false
  redis:
    host: 127.0.0.1
    port: 6379
    password: 123456
  mvc:
    async:
      request-timeout: 20000
mybatis-plus:
  mapper-locations: classpath:com/rabbiter/market/mapper/*Mapper.xml
logging:
  level:
    cn.dingli.market.mapper: debug

